# Generated by Django 4.2.1 on 2023-06-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('id_list1', models.CharField(max_length=10)),
                ('id_list2', models.CharField(max_length=10)),
                ('id_list3', models.CharField(max_length=10)),
                ('id_list4', models.CharField(max_length=10)),
                ('id_list5', models.CharField(max_length=10)),
                ('id_list6', models.CharField(max_length=10)),
                ('id_list7', models.CharField(max_length=10)),
                ('id_list8', models.CharField(max_length=10)),
                ('id_test1', models.CharField(max_length=10)),
                ('id_test2', models.CharField(max_length=10)),
                ('id_test3', models.CharField(max_length=10)),
                ('id_test4', models.CharField(max_length=10)),
                ('id_reav', models.CharField(max_length=10)),
                ('id_final', models.CharField(max_length=10)),
            ],
        ),
    ]
