# Generated by Django 4.2.1 on 2023-06-01 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=3)),
                ('id_huxley', models.IntegerField(default=0)),
                ('list1', models.FloatField(default=0.0)),
                ('list2', models.FloatField(default=0.0)),
                ('list3', models.FloatField(default=0.0)),
                ('list4', models.FloatField(default=0.0)),
                ('list5', models.FloatField(default=0.0)),
                ('list6', models.FloatField(default=0.0)),
                ('list7', models.FloatField(default=0.0)),
                ('list8', models.FloatField(default=0.0)),
                ('test1', models.FloatField(default=0.0)),
                ('test2', models.FloatField(default=0.0)),
                ('test3', models.FloatField(default=0.0)),
                ('test4', models.FloatField(default=0.0)),
                ('reav', models.FloatField(default=0.0)),
                ('final', models.FloatField(default=0.0)),
                ('mean', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('situation', models.CharField(default='EM ANÁLISE', max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classroom')),
            ],
        ),
    ]
