# Generated by Django 4.2 on 2023-06-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_statethread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='list1',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='list2',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='list3',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='list4',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='list5',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='list6',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='list7',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='list8',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='reav',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='test1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='test2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='test3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='test4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
