# Generated by Django 4.2 on 2023-06-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_final_alter_student_list1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='--', max_length=2),
        ),
    ]
